name: zerkalo-dev

services:
  bot:
    build:
      context: ../bot
      dockerfile: dockerfile
    container_name: zerkalo-bot-dev
    env_file:
      - ../bot/.env
    command: npm run dev
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ../bot/src
          target: /app/src
        - action: rebuild
          path: ../bot/package.json
        - action: rebuild
          path: ../bot/package-lock.json
        - action: rebuild
          path: ../bot/tsconfig.json
  api:
    build:
      context: ../api
      dockerfile: dockerfile
    container_name: zerkalo-api-dev
    env_file:
      - ../api/.env
    command: npm run start:dev
    restart: unless-stopped
    ports:
      - 3001:3000
      - 5555:5555 # Для призма студии
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ../api/src
          target: /app/src
        - action: rebuild
          path: ../api/package.json
        - action: rebuild
          path: ../api/package-lock.json
        - action: rebuild
          path: ../api/nest-cli.json
        - action: rebuild
          path: ../api/tsconfig.json
        - action: rebuild
          path: ../api/tsconfig.build.json

  db:
    image: postgres:16
    container_name: zerkalo-db-dev
    restart: unless-stopped
    env_file:
      - ../db/.env
    volumes:
      - zerkalo-db-data-dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d zerkalo"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  zerkalo-db-data-dev:
